# Estamos trabajdno con github actions
# buscamos en github marketplace -> type "Actions" -> AWS --- buscar con tilde azul verificados de aws


name: pipeline to deploy ECR
on: 
  push:
    branches:
      - dev
      - test
      - prod
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: repodiego
          IMAGE_TAG: testtag
        run: |
          docker build -t 339713131846.dkr.ecr.us-east-1.amazonaws.com/repodiego:testtag .
          docker push 339713131846.dkr.ecr.us-east-1.amazonaws.com/repodiego:testtag 
